// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIRNMqjNRfXBB4lEHZESB2UhLAPyErSFM',
    appId: '1:978364652627:web:2d4b9fc286eda51c49baa6',
    messagingSenderId: '978364652627',
    projectId: 'fire-bm-48c62',
    authDomain: 'fire-bm-48c62.firebaseapp.com',
    storageBucket: 'fire-bm-48c62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJTcSG9glRgOFL6flnn2YVUinUmaDRzo',
    appId: '1:978364652627:android:1ed32c3fa8507cca49baa6',
    messagingSenderId: '978364652627',
    projectId: 'fire-bm-48c62',
    storageBucket: 'fire-bm-48c62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCASx59p1NZWK7ewE5UkdBErE3ZAoQg7Do',
    appId: '1:978364652627:ios:383aa4c78cd0496449baa6',
    messagingSenderId: '978364652627',
    projectId: 'fire-bm-48c62',
    storageBucket: 'fire-bm-48c62.appspot.com',
    iosBundleId: 'com.example.bookmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCASx59p1NZWK7ewE5UkdBErE3ZAoQg7Do',
    appId: '1:978364652627:ios:383aa4c78cd0496449baa6',
    messagingSenderId: '978364652627',
    projectId: 'fire-bm-48c62',
    storageBucket: 'fire-bm-48c62.appspot.com',
    iosBundleId: 'com.example.bookmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIRNMqjNRfXBB4lEHZESB2UhLAPyErSFM',
    appId: '1:978364652627:web:a1f52b950edfedf049baa6',
    messagingSenderId: '978364652627',
    projectId: 'fire-bm-48c62',
    authDomain: 'fire-bm-48c62.firebaseapp.com',
    storageBucket: 'fire-bm-48c62.appspot.com',
  );
}
